### PR TITLE
Outrigger.sh front-end styling

### PR DESCRIPTION
**Pull request by joannasaerom**
This PR updates the front-end of the outrigger.sh website to rearrange Bootstrap classes and add Outrigger's brand colors.

### CODE REVIEW

**Comment by grayside** [comment]
Awesome! Can you easily provide a screenshot? I'd love to see what it would look like.

**Comment by joannasaerom** [comment]
@grayside 

Desktop version:
screen shot 2017-03-21 at 10 56 29 am

Mobile version:
screen shot 2017-03-21 at 10 56 40 am

**Comment by grayside** [comment]
Hot stuff, thanks for showing.

**Review by grayside — APPROVED** [review]
There are some spacing inconsistency issues between the scss files, but nothing that should hold up merge.

**Comment by febbraro** [comment]
What builds the SCSS into the styles.css? Is that Jekyll itself?

I ask because it looks like styles.css is the materialized version of your scss.

**Comment by joannasaerom** [comment]
@febbraro I was using sass watch 
```sass --watch scss/styles.scss:css/styles.css```

**Comment by febbraro** [comment]
Are we sure that jekyll just wont handle it if we configure it correctly? That way we dont need an explicit "build step" before committing/pushing which would deploy?

**Comment by joannasaerom** [comment]
@febbraro You're right. I updated the file structure so Jekyll handles it now.

**Comment by febbraro** [comment]
🎉   Thanks @joannasaerom 🎉

**Pull request merged**
